
server:
  port: @server.port@
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: trace

spring:
  cloud:
    gateway:
      discovery: #是否与服务发现组件进行结合
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: user_route
#          uri: lb://user-center
#          predicates:
#            - Path=/users/**


