/*
 * Copyright 2020 聂钊 nz@qdigo.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.qdigo.ebike.third.service.insurance.picc.autoclaim;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-02-26T17:08:52.626+08:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "AutoClaimWebServiceService",
                  wsdlLocation = "http://partnertest.mypicc.com.cn/ecooperation/webservice/autoclaim?wsdl",
                  targetNamespace = "http://webservice.ecooperation.epicc.com.cn/")
public class AutoClaimWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.ecooperation.epicc.com.cn/", "AutoClaimWebServiceService");
    public final static QName AutoClaimWebServicePort = new QName("http://webservice.ecooperation.epicc.com.cn/", "AutoClaimWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://partnertest.mypicc.com.cn/ecooperation/webservice/autoclaim?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AutoClaimWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://partnertest.mypicc.com.cn/ecooperation/webservice/autoclaim?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AutoClaimWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AutoClaimWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutoClaimWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AutoClaimWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AutoClaimWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AutoClaimWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AutoClaimWebService
     */
    @WebEndpoint(name = "AutoClaimWebServicePort")
    public AutoClaimWebService getAutoClaimWebServicePort() {
        return super.getPort(AutoClaimWebServicePort, AutoClaimWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutoClaimWebService
     */
    @WebEndpoint(name = "AutoClaimWebServicePort")
    public AutoClaimWebService getAutoClaimWebServicePort(WebServiceFeature... features) {
        return super.getPort(AutoClaimWebServicePort, AutoClaimWebService.class, features);
    }

}
