/*
 * Copyright 2020 聂钊 nz@qdigo.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.qdigo.ebike.third.service.insurance.picc.print;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-02-26T17:11:16.915+08:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", name = "PrintWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface PrintWebService {

    @WebMethod
    @RequestWrapper(localName = "printPolicyService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "cn.com.epicc.ecooperation.webservice.PrintPolicyService")
    @ResponseWrapper(localName = "printPolicyServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "cn.com.epicc.ecooperation.webservice.PrintPolicyServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String printPolicyService(
            @WebParam(name = "interfaceNo", targetNamespace = "")
                    String interfaceNo,
            @WebParam(name = "datas", targetNamespace = "")
                    String datas
    );
}
