/*
 * Copyright 2020 聂钊 nz@qdigo.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.qdigo.ebike.third.service.insurance.picc.insure;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-02-26T17:04:43.946+08:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "EcooperationWebServiceService",
                  wsdlLocation = "http://partnertest.mypicc.com.cn/ecooperation/webservice/insure?wsdl",
                  targetNamespace = "http://webservice.ecooperation.epicc.com.cn/")
public class EcooperationWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.ecooperation.epicc.com.cn/", "EcooperationWebServiceService");
    public final static QName EcooperationWebServicePort = new QName("http://webservice.ecooperation.epicc.com.cn/", "EcooperationWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://partnertest.mypicc.com.cn/ecooperation/webservice/insure?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EcooperationWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://partnertest.mypicc.com.cn/ecooperation/webservice/insure?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EcooperationWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EcooperationWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EcooperationWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EcooperationWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EcooperationWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EcooperationWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EcooperationWebService
     */
    @WebEndpoint(name = "EcooperationWebServicePort")
    public EcooperationWebService getEcooperationWebServicePort() {
        return super.getPort(EcooperationWebServicePort, EcooperationWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EcooperationWebService
     */
    @WebEndpoint(name = "EcooperationWebServicePort")
    public EcooperationWebService getEcooperationWebServicePort(WebServiceFeature... features) {
        return super.getPort(EcooperationWebServicePort, EcooperationWebService.class, features);
    }

}
