/*
 * Copyright 2020 聂钊 nz@qdigo.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.qdigo.ebike.third.service.insurance.picc.insure;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-02-26T17:04:43.828+08:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", name = "EcooperationWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface EcooperationWebService {

    @WebMethod
    @RequestWrapper(localName = "transitService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "cn.com.epicc.ecooperation.webservice.TransitService")
    @ResponseWrapper(localName = "transitServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "cn.com.epicc.ecooperation.webservice.TransitServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String transitService(
            @WebParam(name = "interfaceNo", targetNamespace = "")
                    String interfaceNo,
            @WebParam(name = "datas", targetNamespace = "")
                    String datas
    );

    @WebMethod
    @RequestWrapper(localName = "shortInsureService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "cn.com.epicc.ecooperation.webservice.ShortInsureService")
    @ResponseWrapper(localName = "shortInsureServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "cn.com.epicc.ecooperation.webservice.ShortInsureServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String shortInsureService(
            @WebParam(name = "interfaceNo", targetNamespace = "")
                    String interfaceNo,
            @WebParam(name = "datas", targetNamespace = "")
                    String datas
    );

    @WebMethod
    @RequestWrapper(localName = "insureService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "cn.com.epicc.ecooperation.webservice.InsureService")
    @ResponseWrapper(localName = "insureServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "cn.com.epicc.ecooperation.webservice.InsureServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String insureService(
            @WebParam(name = "interfaceNo", targetNamespace = "")
                    String interfaceNo,
            @WebParam(name = "datas", targetNamespace = "")
                    String datas
    );

    @WebMethod
    @RequestWrapper(localName = "printProofService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "cn.com.epicc.ecooperation.webservice.PrintProofService")
    @ResponseWrapper(localName = "printProofServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "cn.com.epicc.ecooperation.webservice.PrintProofServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String printProofService(
            @WebParam(name = "interfaceNo", targetNamespace = "")
                    String interfaceNo,
            @WebParam(name = "datas", targetNamespace = "")
                    String datas
    );

    @WebMethod
    @RequestWrapper(localName = "shortModifyService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "cn.com.epicc.ecooperation.webservice.ShortModifyService")
    @ResponseWrapper(localName = "shortModifyServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "cn.com.epicc.ecooperation.webservice.ShortModifyServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String shortModifyService(
            @WebParam(name = "interfaceNo", targetNamespace = "")
                    String interfaceNo,
            @WebParam(name = "datas", targetNamespace = "")
                    String datas
    );

    @WebMethod
    @RequestWrapper(localName = "modifyService", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "cn.com.epicc.ecooperation.webservice.ModifyService")
    @ResponseWrapper(localName = "modifyServiceResponse", targetNamespace = "http://webservice.ecooperation.epicc.com.cn/", className = "cn.com.epicc.ecooperation.webservice.ModifyServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String modifyService(
            @WebParam(name = "interfaceNo", targetNamespace = "")
                    String interfaceNo,
            @WebParam(name = "datas", targetNamespace = "")
                    String datas
    );
}
